title: Data Solutions Lab
email: your-email@example.com
description: Проектирование архитектуры данных и систем принятия решений.
baseurl: "" 
url: "https://datasolutionslab.ru"

# Настройки сборки
markdown: kramdown
theme: minima # Оставляем базу, но будем использовать свой layout
plugins:
  - jekyll-feed