- title: "Проектирование DWH"
  description: "Создание фундамента для работы с данными: от схем хранения до автоматизации ETL/ELT процессов"
  details: "Перевод бизнес-требований на язык техспецификаций и обеспечение чистоты данных."

- title: "Сквозная аналитика и BI"
  description: "Построение отчетности и дашбордов для принятия управленческих решений"
  details: "Сокращение Time-to-Insight и внедрение Data-Driven культуры."